language: objective-c
osx_image: xcode8
install:
- gem install jazzy --no-rdoc --no-ri --no-document
notifications:
  email:
  - john.daub@ovenbits.com
  - jonathan.landon@ovenbits.com
  - ben.kreeger@ovenbits.com
script:
- xcodebuild -project Alexandria.xcodeproj -scheme Alexandria -sdk iphonesimulator10.0
  -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' test
after_success:
- ./Support/create_docs.sh
env:
  global:
    secure: rXlDuY/rnCxgnPmSl2n1RubCvlATIH5pJMB39V5IW1WA7JrCTqCekKWGp5sSik1tu7xdkOENVHJz+a65KEeVHEDxU4KAv8ECRwulKQEO99mDSRmc5X+v5psBr3u3RQwNBZpRMHXKpvyKzuwp1tesjKoMHHppbCmlwQBv+17drMFlnuwnHLZ/NoYAVhB62qLGTtEoOtHKFgSLD9lzaTZL92J3XXTPXU+Wi46Lt6epTMg0ySyDOb49JsysL5edsnyixGw8ub1J2CrT6L0Hrxz1HNkv2i+AMrmCKsI7ZAJrdFHciUB/ARB8TPWOVMmIYtl25YjKFzS5i3K4mRoqsfHsAVbVuFY0ClOveze0VYC9mPNmTrgnObcn/AXkg3LxziJp5QdoRnR5PzbJvkE5l42zLBx3QThPcPB5ggZ5qn7wAiSVZaQT+cil14S2KqRdYp6t2xRUJwdEJ8okmmhBOVqsjRbzhg8+iXeTdqwGV7oHdijFFbwjJnI4weeA73ghP14OVkK6gi/E1Gqcxnil06y0Da3m4Z5B0kWdWyDAdSPVz3QnrV69sRdlFVd+v3yl701ikSOSdzbZf4sj+8HUdl5wWjGoQytAhqbuZd4YHPXHESh0GNYkUZV0y4aSrB1LZdR1NQX1n7Ws418AInm8BXH51/kX2efFjaZhfqprM2ezVxQ=
